### ISSUE TITLE
ロックボタンを押すと結合しているパーツが外れなくなる機能

### ISSUE THREAD

**Issue by hananana** [hananana/mnmy#19]

**Comment by pnrnc485** [comment]
ロックボタンを押した時に結合しているパーツをロックしてください　ロックされた事がわかるように結合点の色を赤から青に変えてください

**Comment by hananana** [comment]
@pnrnc485 この仕様なんだけど、現状のnativeのつくる画面では接続時に赤い点が消えて繋がってるっぽく鎖の画像が表示される仕様なんですが、、ロックしたら青い点が改めて表示されるという認識であってますか？

**Comment by pnrnc485** [comment]
@hananana @flyzion7 
◯ロックボタン
ロック中の仕様
・左上にロック中の表示を出す（イメージは後ほど共有します）
・ロックされている接続点は赤い点が表示されなくなる
・ロックボタンが「ロック中」表記になり、アイコンの色が黒から「パーツを追加」と同じ赤になる。またアイコンが閉じている鍵表示になる（素材は週明けに共有します）

上記に伴うロック中以外の仕様で変更点
・現在赤い点が接続パーツの後ろにあるが前面に出す（ロック中と明確に違いがわかるようにしたい）


この仕様で確定です
