### ISSUE TITLE
ピンチイン、アウトした時の動作修正

### ISSUE THREAD

**Issue by pnrnc485** [hananana/mnmy#45]
右上基準で縮尺しているのを左上にする　ルーラーの角が常に左上にあるようにする

パーツは真ん中寄せ

**Comment by hananana** [comment]
@pnrnc485 
> ルーラーの角が常に左上にあるようにする
これはルーラーは常に角が左上固定でかつ、画面の拡大縮小にあわせてルーラーも拡大縮小するということであってます？

> パーツは真ん中寄せ
これは拡大縮小するとパーツが移動するって認識であってますでしょうか？

**Comment by pnrnc485** [comment]
@hananana 

ルーラーはその認識であってます

パーツ真ん中寄せの件は忘れてくださいなー
