### ISSUE TITLE
ボタンを押すとレイヤの順番を入れ替えることができる

### ISSUE THREAD

**Issue by hananana** [hananana/mnmy#6]

**Comment by flyzion7** [comment]
縮小・削除ボタンみたいなボタンで、タップすると選択しているパーツが変わる(パーツを囲っている赤い印が変わる)イメージですか？

**Comment by flyzion7** [comment]
ベース以外のパーツが順番にzOrderが変わります。

**Comment by hananana** [comment]
https://prottapp.com/p/5d1509#/s/5624b418696463304b110200
この機能なんですが、ZOrderを前に移動する機能＆後ろに移動する感じです。（前へボタンと後ろへボタンですね）

**Comment by flyzion7** [comment]
修正しました。前面・背面ボタンで1つづつ順番入れ替えてます。
