### ISSUE TITLE
大きいパーツをベースから外すと床を貫通して何処かえきえてしまう

### ISSUE THREAD

**Issue by pnrnc485** [hananana/mnmy#67]

**Comment by flyzion7** [comment]
大きいパーツの剛体が床の剛体と重なっているときに手を離すと床下へ消える。
大きいパーツを移動中に手を離して、画面中心に移動させると、たまにベースと接続されてします。
なので、重なっている状態で手を離すと、真上方向の力を加えるようにしてます。
現状のmonomyでも大きいパーツが消えることがあるので、このままにしておきます。
