### ISSUE TITLE
削除ボタンで選択したパーツを消すことができる

### ISSUE THREAD

**Issue by hananana** [hananana/mnmy#8]

**Comment by flyzion7** [comment]
削除ボタンを押すと、選択している状態(赤い矩形で囲まれたパーツ)のパーツが削除される感じで大丈夫ですか？

**Comment by hananana** [comment]
問題ないですっ

**Comment by flyzion7** [comment]
パーツを削除すると、詳細ボタンがある黒枠を消せばいいんですかね？？
とりあえず、黒枠を消すようにしておきます〜
